services:
#───────────────────────────────────────────────────────────────────────────────
#  Front-end  (Next.js)
#───────────────────────────────────────────────────────────────────────────────
  frontend:
    image: neaitaskbot/taskbot-portal:1.0
    container_name: taskbot-frontend
    environment:
      NODE_ENV: production
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: unless-stopped

#───────────────────────────────────────────────────────────────────────────────
#  Python installer / licence API  (Flask)
#───────────────────────────────────────────────────────────────────────────────
  installer:
    image: neaitaskbot/taskbot-installer:1.0
    container_name: taskbot-installer
    environment:
      TASKBOT_DEPLOY_MODE: ${TASKBOT_DEPLOY_MODE:-ONPREMISE}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT:-5000}
    volumes:
      - installer-data:/data
      - ./keys:/etc/taskbot/keys:ro
      - ./certs:/etc/taskbot/certs:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: unless-stopped

#───────────────────────────────────────────────────────────────────────────────
#  Java Taskbot Gateway (Spring Boot)
#───────────────────────────────────────────────────────────────────────────────
  gateway:
    image: neaitaskbot/taskbot-gw:1.0
    container_name: taskbot-gateway
    environment:
      CORE_API_URL: "http://taskbot-api-service:${TASKBOT_API_INTERNAL_PORT:-18902}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    depends_on:
      - taskbot-api-service
    restart: unless-stopped

#───────────────────────────────────────────────────────────────────────────────
#  Java Taskbot API Service (FULLY DYNAMIC)
#───────────────────────────────────────────────────────────────────────────────
  taskbot-api-service:
    image: neaitaskbot/taskbot-api:1.0
    container_name: taskbot-api-service
    restart: unless-stopped
    # This block is now fully dynamic, reading all values from the .env file
    env_file:
      - .env
    volumes:
      - uploads-data:/storage/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    depends_on:
      - mariadb
      - redis
      - rabbitmq
      - mongodb

#───────────────────────────────────────────────────────────────────────────────
#  Databases & Queues (UPDATED CREDENTIALS & PORTS)
#───────────────────────────────────────────────────────────────────────────────
  mariadb:
    image: mariadb:10.6 # Using a standard, versioned image is often more stable
    container_name: taskbot-mariadb
    restart: unless-stopped
    environment:
      # Use the new credentials from the .env file
      MYSQL_ROOT_PASSWORD: "${JDBC_PWD}"
      MYSQL_DATABASE: "nucleus" # This name is fixed in the JDBC_URL
      MYSQL_USER: "${JDBC_USR}"
      MYSQL_PASSWORD: "${JDBC_PWD}"
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: taskbot-redis
    restart: unless-stopped
    # Use the new password and specify the internal port
    command: ["redis-server", "--port", "6379", "--requirepass", "${REDIS_PWD}"]
    ports:
      - "26379:6379" # Expose the new port 26379
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: taskbot-rabbitmq
    restart: unless-stopped
    environment:
      # Use the new credentials from the .env file
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USERNAME}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
    ports:
      - "15672:15672" # Management UI

  mongodb:
    image: mongo:4.4
    container_name: taskbot-mongodb
    restart: unless-stopped
    environment:
      # Use the new credentials from the .env file
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - mongodb-data:/data/db

#───────────────────────────────────────────────────────────────────────────────
#  Nginx reverse-proxy (No changes needed here)
#───────────────────────────────────────────────────────────────────────────────
  nginx:
    image: nginx:1.27-alpine
    # ... (rest of service is unchanged)

volumes:
  installer-data:
  uploads-data:
  mariadb-data:
  redis-data:
  rabbitmq-data:
  mongodb-data: